export const FETCH_APPLICATIONS = 'APPS/FETCH_APPLICATIONS';

export const FETCH_OFFERS = 'OFFERS/FETCH_OFFERS';
export const CREATE_OFFER = 'OFFERS/CREATE_OFFER';

export const FETCH_NETWORKS = 'OFFERS/FETCH_NETWORKS';
export const CREATE_NETWORK = 'OFFERS/CREATE_NETWORK';

// TODO: реализовать редактирование
// export const EDIT_OFFER = 'OFFERS/EDIT_OFFER';
// export const EDIT_NETWORK = 'OFFERS/EDIT_NETWORK';

export const CHANGE_LOCALE = 'APP/CHANGE_LOCALE';

export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';

export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';

export const TOGGLE_THEME = 'APP/TOGGLE_THEME';
